# Copyright 2026 Philterd, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
PhiSQL v1.0 parser.

The lexer and parser are generated by ANTLR from the canonical grammar at
``spec/v1.0/grammar/PhiSQL.g4`` and live under :mod:`phisql._generated` (see
``scripts/generate_parser.sh``). This module drives the generated parser and
walks the resulting parse tree with :class:`_AstBuilder` to produce the same
:mod:`phisql.ast` node tree the compiler consumes. Using the generated parser is
the load-bearing assertion that this implementation cannot drift from the
grammar, the same role the generated parser plays in the Java reference.

Syntax errors raise :class:`~phisql.errors.ParseException` with a ``line L:C``
prefix (1-based line, 0-based column, matching ANTLR's ``charPositionInLine``).
"""

from __future__ import annotations

from antlr4 import CommonTokenStream, InputStream
from antlr4.error.ErrorListener import ErrorListener

from . import ast
from ._generated.PhiSQLLexer import PhiSQLLexer
from ._generated.PhiSQLParser import PhiSQLParser
from ._generated.PhiSQLVisitor import PhiSQLVisitor
from .errors import ParseException


class _RaisingErrorListener(ErrorListener):
    """Turns the first lexer/parser error into a ``ParseException``.

    Raising on the first ``syntaxError`` (rather than collecting and recovering)
    gives single-error, fail-fast diagnostics with the ``line L:C`` prefix the
    rest of the reference implementation reports.
    """

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):
        raise ParseException(f"line {line}:{column} {msg}")


_ERROR_LISTENER = _RaisingErrorListener()


class _AstBuilder(PhiSQLVisitor):
    """Builds a :mod:`phisql.ast` tree from an ANTLR parse tree.

    There is one ``visit*`` method per grammar rule the compiler cares about.
    Token text is taken verbatim (quotes included for string literals, raw text
    for numbers); the compiler unquotes and coerces it later, matching the Java
    reference's use of ``getText()``.
    """

    # --- document / statement dispatch ---------------------------------------

    def visitDocument(self, ctx) -> ast.Document:
        return ast.Document(statements=[self.visit(s) for s in ctx.statement()])

    def visitStatement(self, ctx):
        # `statement` is a single matched sub-statement rule; dispatch to it.
        return self.visit(ctx.getChild(0))

    # --- policyDecl ----------------------------------------------------------

    def visitPolicyDecl(self, ctx) -> ast.PolicyDecl:
        return ast.PolicyDecl(
            policy_name=ctx.policyName.text,
            description_raw=ctx.description.text if ctx.description is not None else None,
        )

    # --- configureStmt -------------------------------------------------------

    def visitConfigureStmt(self, ctx) -> ast.ConfigureStmt:
        stmt = ast.ConfigureStmt()
        if ctx.cryptoKeyEnv is not None:
            stmt.crypto_key_env_raw = ctx.cryptoKeyEnv.text
        elif ctx.fpeKeyEnv is not None:
            stmt.fpe_key_env_raw = ctx.fpeKeyEnv.text
            stmt.fpe_tweak_env_raw = ctx.fpeTweakEnv.text
        elif ctx.GRAPHICAL() is not None:
            stmt.graphical_box = True
            stmt.settings = self.visit(ctx.settingList())
        else:  # config block: SPLITTING | PDF | POSTFILTERS | ANALYSIS
            stmt.config_block = ctx.configBlock.text.upper()
            stmt.settings = self.visit(ctx.settingList())
        return stmt

    # --- settingList / setting / settingValue --------------------------------

    def visitSettingList(self, ctx) -> list:
        return [self.visit(s) for s in ctx.setting()]

    def visitSetting(self, ctx) -> ast.Setting:
        return ast.Setting(key=self.visit(ctx.settingKey()),
                           value=self.visit(ctx.settingValue()))

    def visitSettingKey(self, ctx) -> ast.SettingKey:
        if ctx.ID() is not None:
            return ast.SettingKey(kind="ID", text=ctx.ID().getText())
        return ast.SettingKey(kind="STRING", text=ctx.STRING_LITERAL().getText())

    def visitSettingValue(self, ctx) -> ast.SettingValue:
        if ctx.literal() is not None:
            return ast.SettingValue(literal=self.visit(ctx.literal()))
        if ctx.objectValue() is not None:
            return ast.SettingValue(
                object_settings=self.visit(ctx.objectValue().settingList()))
        return ast.SettingValue(
            array_elements=[self.visit(v) for v in ctx.arrayValue().settingValue()])

    def visitLiteral(self, ctx) -> ast.Literal:
        if ctx.STRING_LITERAL() is not None:
            return ast.Literal("STRING", ctx.STRING_LITERAL().getText())
        if ctx.NUMERIC_LITERAL() is not None:
            return ast.Literal("NUMERIC", ctx.NUMERIC_LITERAL().getText())
        if ctx.BOOLEAN_LITERAL() is not None:
            return ast.Literal("BOOLEAN", ctx.BOOLEAN_LITERAL().getText())
        return ast.Literal("ID", ctx.ID().getText())

    def _options(self, ctx):
        """The OPTIONS setting list for a statement, or None when absent."""
        clause = ctx.optionsClause()
        return self.visit(clause.settingList()) if clause is not None else None

    # --- redactStmt ----------------------------------------------------------

    def visitRedactStmt(self, ctx) -> ast.RedactStmt:
        return ast.RedactStmt(
            entities=self.visit(ctx.entityList()),
            strategy=self.visit(ctx.strategyExpr()) if ctx.strategyExpr() is not None else None,
            predicate=self.visit(ctx.predicate()) if ctx.predicate() is not None else None,
            options=self._options(ctx),
        )

    # --- deidentifyStmt ------------------------------------------------------

    def visitDeidentifyStmt(self, ctx) -> ast.DeidentifyStmt:
        return ast.DeidentifyStmt(
            assignments=[self.visit(a) for a in ctx.entityAssignment()])

    def visitEntityAssignment(self, ctx) -> ast.EntityAssignment:
        return ast.EntityAssignment(
            entity=self.visit(ctx.entityType()),
            strategy=self.visit(ctx.strategyExpr()),
            options=self._options(ctx),
        )

    # --- ignoreStmt ----------------------------------------------------------

    def visitIgnoreStmt(self, ctx) -> ast.IgnoreStmt:
        if ctx.TERMS() is not None:
            stmt = ast.IgnoreStmt(kind="TERMS", terms=self.visit(ctx.stringList()))
        else:
            stmt = ast.IgnoreStmt(kind="PATTERN",
                                  pattern_raw=ctx.STRING_LITERAL().getText())
        if ctx.entityList() is not None:
            stmt.entities = self.visit(ctx.entityList())
        stmt.options = self._options(ctx)
        return stmt

    # --- defineIdentifierStmt / defineDictionaryStmt / defineSectionStmt ------

    def visitDefineIdentifierStmt(self, ctx) -> ast.DefineIdentifierStmt:
        return ast.DefineIdentifierStmt(
            classification_raw=ctx.classification.text,
            pattern_raw=ctx.pattern.text,
            group_number=ctx.groupNumber.text if ctx.groupNumber is not None else None,
            sensitivity=ctx.sensitivity.text.upper() if ctx.sensitivity is not None else None,
            strategy=self.visit(ctx.strategyExpr()),
            predicate=self.visit(ctx.predicate()) if ctx.predicate() is not None else None,
            options=self._options(ctx),
        )

    def visitDefineDictionaryStmt(self, ctx) -> ast.DefineDictionaryStmt:
        return ast.DefineDictionaryStmt(
            classification_raw=ctx.classification.text,
            terms=self.visit(ctx.stringList()),
            fuzzy=ctx.FUZZY() is not None,
            sensitivity=ctx.sensitivity.text if ctx.sensitivity is not None else None,
            capitalized=ctx.CAPITALIZED() is not None,
            strategy=self.visit(ctx.strategyExpr()),
            options=self._options(ctx),
        )

    def visitDefineSectionStmt(self, ctx) -> ast.DefineSectionStmt:
        return ast.DefineSectionStmt(
            start_raw=ctx.startPattern.text,
            end_raw=ctx.endPattern.text,
            strategy=self.visit(ctx.strategyExpr()),
            options=self._options(ctx),
        )

    # --- detectStmt ----------------------------------------------------------

    def visitDetectStmt(self, ctx) -> ast.DetectStmt:
        return ast.DetectStmt(
            labels=self.visit(ctx.stringList()) if ctx.stringList() is not None else None,
            endpoint_raw=ctx.endpoint.text if ctx.endpoint is not None else None,
            strategy=self.visit(ctx.strategyExpr()),
            predicate=self.visit(ctx.predicate()) if ctx.predicate() is not None else None,
            options=self._options(ctx),
        )

    # --- entityList / entityType ---------------------------------------------

    def visitEntityList(self, ctx) -> list:
        return [self.visit(e) for e in ctx.entityType()]

    def visitSimpleEntityType(self, ctx) -> ast.SimpleEntityType:
        return ast.SimpleEntityType(name=ctx.ID().getText())

    def visitCustomIdentifier(self, ctx) -> ast.CustomIdentifier:
        return ast.CustomIdentifier(classification_raw=ctx.STRING_LITERAL().getText())

    # --- strategyExpr --------------------------------------------------------

    def visitStrategyExpr(self, ctx) -> ast.StrategyExpr:
        args = self.visit(ctx.strategyArgs()) if ctx.strategyArgs() is not None else []
        return ast.StrategyExpr(name=ctx.strategyName().getText(), args=args)

    def visitStrategyArgs(self, ctx) -> list:
        return [self.visit(a) for a in ctx.namedArg()]

    def visitNamedArg(self, ctx) -> ast.NamedArg:
        return ast.NamedArg(arg_name=ctx.argName.text,
                            value=self.visit(ctx.settingValue()))

    # --- predicate (redaction WHERE) -----------------------------------------

    def visitConfidencePredicate(self, ctx) -> ast.ConfidencePredicate:
        return ast.ConfidencePredicate(op=self.visit(ctx.compareOp()),
                                       number=ctx.NUMERIC_LITERAL().getText())

    def visitParenPredicate(self, ctx) -> ast.ParenPredicate:
        return ast.ParenPredicate(inner=self.visit(ctx.predicate()))

    def visitLogicalPredicate(self, ctx) -> ast.LogicalPredicate:
        op = "AND" if ctx.AND() is not None else "OR"
        return ast.LogicalPredicate(op=op,
                                    left=self.visit(ctx.predicate(0)),
                                    right=self.visit(ctx.predicate(1)))

    def visitCompareOp(self, ctx) -> str:
        return ctx.getText()

    # --- stringList ----------------------------------------------------------

    def visitStringList(self, ctx) -> list:
        return [t.getText() for t in ctx.STRING_LITERAL()]

    # --- discoveryStmt -------------------------------------------------------
    #
    # Discovery statements parse (and are validated) by the generated parser but
    # are not translated by the compiler; only the verb is retained, matching
    # the Java reference's scope.

    def visitFindPiiStmt(self, ctx) -> ast.DiscoveryStmt:
        return ast.DiscoveryStmt(verb="FIND_PII")

    def visitDiscoverEntitiesStmt(self, ctx) -> ast.DiscoveryStmt:
        return ast.DiscoveryStmt(verb="DISCOVER_ENTITIES")

    def visitScanStmt(self, ctx) -> ast.DiscoveryStmt:
        return ast.DiscoveryStmt(verb="SCAN")

    def visitSelectFindingsStmt(self, ctx) -> ast.DiscoveryStmt:
        return ast.DiscoveryStmt(verb="SELECT_FINDINGS")


def parse(source: str) -> ast.Document:
    """Lexes and parses ``source`` into a :class:`ast.Document`."""
    lexer = PhiSQLLexer(InputStream(source))
    lexer.removeErrorListeners()
    lexer.addErrorListener(_ERROR_LISTENER)

    parser = PhiSQLParser(CommonTokenStream(lexer))
    parser.removeErrorListeners()
    parser.addErrorListener(_ERROR_LISTENER)

    tree = parser.document()
    return _AstBuilder().visit(tree)
