// Copyright 2026 Philterd, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using Antlr4.Runtime;
using Antlr4.Runtime.Tree;
using Philterd.PhiSql.Ast;
using Philterd.PhiSql.Generated;

namespace Philterd.PhiSql;

/// <summary>
/// PhiSQL v1.0 parser. The lexer and parser are generated by ANTLR from the
/// canonical grammar at <c>spec/v1.0/grammar/PhiSQL.g4</c> and live under
/// <see cref="Philterd.PhiSql.Generated"/> (see <c>scripts/generate_parser.sh</c>).
/// <see cref="Parse"/> drives the generated parser and walks the parse tree with
/// <c>AstBuilder</c> into the same <see cref="Document"/> AST the compiler
/// consumes. Using the generated parser is the load-bearing assertion that this
/// implementation cannot drift from the grammar. Syntax errors throw
/// <see cref="ParseException"/> with a <c>line L:C</c> prefix (1-based line,
/// 0-based column).
/// </summary>
public sealed class Parser
{
    /// <summary>Lexes and parses <paramref name="source"/> into a document AST.</summary>
    public static Document Parse(string source)
    {
        var lexer = new PhiSQLLexer(new AntlrInputStream(source));
        lexer.RemoveErrorListeners();
        lexer.AddErrorListener(ThrowingErrorListener.Instance);

        var parser = new PhiSQLParser(new CommonTokenStream(lexer));
        parser.RemoveErrorListeners();
        parser.AddErrorListener(ThrowingErrorListener.Instance);

        PhiSQLParser.DocumentContext tree = parser.document();
        return (Document)new AstBuilder().Visit(tree)!;
    }

    /// <summary>
    /// Turns the first lexer/parser error into a <see cref="ParseException"/>.
    /// Throwing on the first error (rather than recovering) gives single-error,
    /// fail-fast diagnostics with the <c>line L:C</c> prefix the rest of the
    /// reference implementation reports.
    /// </summary>
    private sealed class ThrowingErrorListener : IAntlrErrorListener<int>, IAntlrErrorListener<IToken>
    {
        public static readonly ThrowingErrorListener Instance = new();

        public void SyntaxError(TextWriter output, IRecognizer recognizer, int offendingSymbol,
            int line, int charPositionInLine, string msg, RecognitionException e)
            => throw new ParseException($"line {line}:{charPositionInLine} {msg}");

        public void SyntaxError(TextWriter output, IRecognizer recognizer, IToken offendingSymbol,
            int line, int charPositionInLine, string msg, RecognitionException e)
            => throw new ParseException($"line {line}:{charPositionInLine} {msg}");
    }

    /// <summary>
    /// Builds a <see cref="Document"/> AST from an ANTLR parse tree. There is one
    /// <c>Visit*</c> method per grammar rule the compiler cares about. Token text
    /// is taken verbatim (quotes included for string literals, raw text for
    /// numbers); the compiler unquotes and coerces it later.
    /// </summary>
    private sealed class AstBuilder : PhiSQLBaseVisitor<object?>
    {
        private T V<T>(IParseTree tree) => (T)Visit(tree)!;

        private List<Setting>? OptionsOf(PhiSQLParser.OptionsClauseContext? ctx)
            => ctx is null ? null : V<List<Setting>>(ctx);

        // --- document / statement dispatch -----------------------------------

        public override object? VisitDocument(PhiSQLParser.DocumentContext ctx)
        {
            var doc = new Document();
            foreach (PhiSQLParser.StatementContext s in ctx.statement())
                doc.Statements.Add(V<IStatement>(s));
            return doc;
        }

        public override object? VisitStatement(PhiSQLParser.StatementContext ctx)
            => Visit(ctx.GetChild(0)); // single matched sub-statement rule

        // --- policyDecl ------------------------------------------------------

        public override object? VisitPolicyDecl(PhiSQLParser.PolicyDeclContext ctx)
            => new PolicyDecl
            {
                PolicyName = ctx.policyName.Text,
                DescriptionRaw = ctx.description?.Text,
            };

        // --- configureStmt ---------------------------------------------------

        public override object? VisitConfigureStmt(PhiSQLParser.ConfigureStmtContext ctx)
        {
            var stmt = new ConfigureStmt();
            if (ctx.cryptoKeyEnv is not null)
            {
                stmt.CryptoKeyEnvRaw = ctx.cryptoKeyEnv.Text;
            }
            else if (ctx.fpeKeyEnv is not null)
            {
                stmt.FpeKeyEnvRaw = ctx.fpeKeyEnv.Text;
                stmt.FpeTweakEnvRaw = ctx.fpeTweakEnv.Text;
            }
            else if (ctx.GRAPHICAL() is not null)
            {
                stmt.GraphicalBox = true;
                stmt.Settings = V<List<Setting>>(ctx.settingList());
            }
            else // config block: SPLITTING | PDF | POSTFILTERS | ANALYSIS
            {
                stmt.ConfigBlock = ctx.configBlock.Text.ToUpperInvariant();
                stmt.Settings = V<List<Setting>>(ctx.settingList());
            }
            return stmt;
        }

        // --- settingList / setting / settingValue ----------------------------

        public override object? VisitSettingList(PhiSQLParser.SettingListContext ctx)
        {
            var list = new List<Setting>();
            foreach (PhiSQLParser.SettingContext s in ctx.setting())
                list.Add(V<Setting>(s));
            return list;
        }

        public override object? VisitSetting(PhiSQLParser.SettingContext ctx)
            => new Setting
            {
                Key = V<SettingKey>(ctx.settingKey()),
                Value = V<SettingValue>(ctx.settingValue()),
            };

        public override object? VisitSettingKey(PhiSQLParser.SettingKeyContext ctx)
            => ctx.ID() is not null
                ? new SettingKey { Kind = SettingKeyKind.Id, Text = ctx.ID().GetText() }
                : new SettingKey { Kind = SettingKeyKind.String, Text = ctx.STRING_LITERAL().GetText() };

        public override object? VisitSettingValue(PhiSQLParser.SettingValueContext ctx)
        {
            if (ctx.literal() is { } lit)
                return new SettingValue { Literal = V<Literal>(lit) };
            if (ctx.objectValue() is { } obj)
                return new SettingValue { ObjectSettings = V<List<Setting>>(obj.settingList()) };

            var elements = new List<SettingValue>();
            foreach (PhiSQLParser.SettingValueContext v in ctx.arrayValue().settingValue())
                elements.Add(V<SettingValue>(v));
            return new SettingValue { ArrayElements = elements };
        }

        public override object? VisitLiteral(PhiSQLParser.LiteralContext ctx)
        {
            if (ctx.STRING_LITERAL() is not null)
                return new Literal { Kind = LiteralKind.String, Text = ctx.STRING_LITERAL().GetText() };
            if (ctx.NUMERIC_LITERAL() is not null)
                return new Literal { Kind = LiteralKind.Numeric, Text = ctx.NUMERIC_LITERAL().GetText() };
            if (ctx.BOOLEAN_LITERAL() is not null)
                return new Literal { Kind = LiteralKind.Boolean, Text = ctx.BOOLEAN_LITERAL().GetText() };
            return new Literal { Kind = LiteralKind.Id, Text = ctx.ID().GetText() };
        }

        public override object? VisitOptionsClause(PhiSQLParser.OptionsClauseContext ctx)
            => V<List<Setting>>(ctx.settingList());

        // --- redactStmt ------------------------------------------------------

        public override object? VisitRedactStmt(PhiSQLParser.RedactStmtContext ctx)
            => new RedactStmt
            {
                Entities = V<List<IEntityType>>(ctx.entityList()),
                Strategy = ctx.strategyExpr() is { } se ? V<StrategyExpr>(se) : null,
                Predicate = ctx.predicate() is { } p ? V<IPredicate>(p) : null,
                Options = OptionsOf(ctx.optionsClause()),
            };

        // --- deidentifyStmt --------------------------------------------------

        public override object? VisitDeidentifyStmt(PhiSQLParser.DeidentifyStmtContext ctx)
        {
            var assignments = new List<EntityAssignment>();
            foreach (PhiSQLParser.EntityAssignmentContext a in ctx.entityAssignment())
                assignments.Add(V<EntityAssignment>(a));
            return new DeidentifyStmt { Assignments = assignments };
        }

        public override object? VisitEntityAssignment(PhiSQLParser.EntityAssignmentContext ctx)
            => new EntityAssignment
            {
                Entity = V<IEntityType>(ctx.entityType()),
                Strategy = V<StrategyExpr>(ctx.strategyExpr()),
                Options = OptionsOf(ctx.optionsClause()),
            };

        // --- ignoreStmt ------------------------------------------------------

        public override object? VisitIgnoreStmt(PhiSQLParser.IgnoreStmtContext ctx)
        {
            IgnoreStmt stmt = ctx.TERMS() is not null
                ? new IgnoreStmt { Kind = "TERMS", Terms = V<List<string>>(ctx.stringList()) }
                : new IgnoreStmt { Kind = "PATTERN", PatternRaw = ctx.STRING_LITERAL().GetText() };
            if (ctx.entityList() is { } el)
                stmt.Entities = V<List<IEntityType>>(el);
            stmt.Options = OptionsOf(ctx.optionsClause());
            return stmt;
        }

        // --- defineIdentifierStmt / defineDictionaryStmt / defineSectionStmt --

        public override object? VisitDefineIdentifierStmt(PhiSQLParser.DefineIdentifierStmtContext ctx)
            => new DefineIdentifierStmt
            {
                ClassificationRaw = ctx.classification.Text,
                PatternRaw = ctx.pattern.Text,
                GroupNumber = ctx.groupNumber?.Text,
                Sensitivity = ctx.sensitivity?.Text.ToUpperInvariant(),
                Strategy = V<StrategyExpr>(ctx.strategyExpr()),
                Predicate = ctx.predicate() is { } p ? V<IPredicate>(p) : null,
                Options = OptionsOf(ctx.optionsClause()),
            };

        public override object? VisitDefineDictionaryStmt(PhiSQLParser.DefineDictionaryStmtContext ctx)
            => new DefineDictionaryStmt
            {
                ClassificationRaw = ctx.classification.Text,
                Terms = V<List<string>>(ctx.stringList()),
                Fuzzy = ctx.FUZZY() is not null,
                Sensitivity = ctx.sensitivity?.Text,
                Capitalized = ctx.CAPITALIZED() is not null,
                Strategy = V<StrategyExpr>(ctx.strategyExpr()),
                Options = OptionsOf(ctx.optionsClause()),
            };

        public override object? VisitDefineSectionStmt(PhiSQLParser.DefineSectionStmtContext ctx)
            => new DefineSectionStmt
            {
                StartRaw = ctx.startPattern.Text,
                EndRaw = ctx.endPattern.Text,
                Strategy = V<StrategyExpr>(ctx.strategyExpr()),
                Options = OptionsOf(ctx.optionsClause()),
            };

        // --- detectStmt ------------------------------------------------------

        public override object? VisitDetectStmt(PhiSQLParser.DetectStmtContext ctx)
            => new DetectStmt
            {
                Labels = ctx.stringList() is { } sl ? V<List<string>>(sl) : null,
                EndpointRaw = ctx.endpoint?.Text,
                ModelRaw = ctx.model?.Text,
                Strategy = V<StrategyExpr>(ctx.strategyExpr()),
                Predicate = ctx.predicate() is { } p ? V<IPredicate>(p) : null,
                Options = OptionsOf(ctx.optionsClause()),
            };

        // --- entityList / entityType -----------------------------------------

        public override object? VisitEntityList(PhiSQLParser.EntityListContext ctx)
        {
            var entities = new List<IEntityType>();
            foreach (PhiSQLParser.EntityTypeContext e in ctx.entityType())
                entities.Add(V<IEntityType>(e));
            return entities;
        }

        public override object? VisitSimpleEntityType(PhiSQLParser.SimpleEntityTypeContext ctx)
            => new SimpleEntityType { Name = ctx.ID().GetText() };

        public override object? VisitCustomIdentifier(PhiSQLParser.CustomIdentifierContext ctx)
            => new CustomIdentifier { ClassificationRaw = ctx.STRING_LITERAL().GetText() };

        // --- strategyExpr ----------------------------------------------------

        public override object? VisitStrategyExpr(PhiSQLParser.StrategyExprContext ctx)
        {
            var args = ctx.strategyArgs() is { } sa ? V<List<NamedArg>>(sa) : new List<NamedArg>();
            return new StrategyExpr { Name = ctx.strategyName().GetText(), Args = args };
        }

        public override object? VisitStrategyArgs(PhiSQLParser.StrategyArgsContext ctx)
        {
            var args = new List<NamedArg>();
            foreach (PhiSQLParser.NamedArgContext a in ctx.namedArg())
                args.Add(V<NamedArg>(a));
            return args;
        }

        public override object? VisitNamedArg(PhiSQLParser.NamedArgContext ctx)
            => new NamedArg
            {
                ArgName = ctx.argName.Text,
                Value = V<SettingValue>(ctx.settingValue()),
            };

        // --- predicate (redaction WHERE) -------------------------------------

        public override object? VisitConfidencePredicate(PhiSQLParser.ConfidencePredicateContext ctx)
            => new ConfidencePredicate
            {
                Op = V<string>(ctx.compareOp()),
                Number = ctx.NUMERIC_LITERAL().GetText(),
            };

        public override object? VisitParenPredicate(PhiSQLParser.ParenPredicateContext ctx)
            => new ParenPredicate { Inner = V<IPredicate>(ctx.predicate()) };

        public override object? VisitLogicalPredicate(PhiSQLParser.LogicalPredicateContext ctx)
            => new LogicalPredicate
            {
                Op = ctx.AND() is not null ? "AND" : "OR",
                Left = V<IPredicate>(ctx.predicate(0)),
                Right = V<IPredicate>(ctx.predicate(1)),
            };

        public override object? VisitCompareOp(PhiSQLParser.CompareOpContext ctx)
            => ctx.GetText();

        // --- stringList ------------------------------------------------------

        public override object? VisitStringList(PhiSQLParser.StringListContext ctx)
            => ctx.STRING_LITERAL().Select(t => t.GetText()).ToList();

        // --- discoveryStmt ---------------------------------------------------
        //
        // Discovery statements parse (and are validated) by the generated parser
        // but are not translated by the compiler; only the verb is retained.

        public override object? VisitFindPiiStmt(PhiSQLParser.FindPiiStmtContext ctx)
            => new DiscoveryStmt { Verb = "FIND_PII" };

        public override object? VisitDiscoverEntitiesStmt(PhiSQLParser.DiscoverEntitiesStmtContext ctx)
            => new DiscoveryStmt { Verb = "DISCOVER_ENTITIES" };

        public override object? VisitScanStmt(PhiSQLParser.ScanStmtContext ctx)
            => new DiscoveryStmt { Verb = "SCAN" };

        public override object? VisitSelectFindingsStmt(PhiSQLParser.SelectFindingsStmtContext ctx)
            => new DiscoveryStmt { Verb = "SELECT_FINDINGS" };
    }
}
